- name: install curl
  apt: name=curl state=present

- name: prepare nodejs v6.x
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

- name: install nodejs
  apt: name=nodejs state=present

- name: add nodejs user
  user: name=nodejs comment="for nodejs executor" group=dialout
